### ISSUE TITLE
シェアされたルールがGM画面の初期割当欄に表示される

### ISSUE THREAD

**Issue by y3eadgbe** [haggle-de-haghag/haggle-de-haghag#1]
ルールが ASSIGNED か SHARED かに関わらずGM画面の初期割当チェックボックスが enable されるようです

**Comment by osak** [comment]
確かに

**Comment by osak** [comment]
そもそもゲーム開始後にGMが「初期」割り当てをいじれるのはおかしい気がしますね

**Comment by osak** [comment]
#3 あたりとの兼ね合いで後で変えるかもしれないけど、とりあえずASSIGNEDな割り当てしかいじれないようにしました
