### ISSUE TITLE
ルール文章の長さに現実的な上限を設ける

### ISSUE THREAD

**Issue by y3eadgbe** [haggle-de-haghag/haggle-de-haghag#2]
現状ルール文章に現実的な上限がなく、少なくとも数MBのルールを設定できます。
（他のフィールドは varchar のリミットで制限されていますが、Postgre の text型には上限がないようです）

**Comment by osak** [comment]
そもそも巨大リクエストを送られると困るので、リクエストサイズ自体に上限をかけるのがよさそう

**Comment by osak** [comment]
あんまりルールが長くてもアレだし、リクエスト上限を小さくしすぎても変なハマり方をしそうなのでやっぱり上限かけたほうがよさそう。とりあえずUTF-8で1000 bytesくらいですかね。制限かけるならバイト数カウントもUIに付けたいところ。
