### ISSUE TITLE
ルールを渡せるようにする

### ISSUE THREAD

**Issue by mkut** [haggle-de-haghag/haggle-de-haghag#3]
ルール以外のオブジェクトもルール扱いすることでいろいろできそう。

**Comment by osak** [comment]
トークンの類をやり取りすることを考えると、(種類, 個数)で管理されるトークンという概念を作ると便利そう。

トークンがテキストを持てるようにするとルール自体もトークンの一種として処理できそうな気がするけど、こっちはやる前にもう少し深く考えるべきですね。

**Comment by osak** [comment]
受け渡しできるトークンを実装しました。
